### ISSUE TITLE
Target must not be null. NativeAd 

### ISSUE THREAD

**Issue by IhaYarre** [ItzNotABug/HouseAds#15]
java.lang.IllegalArgumentException: Target must not be null.
        at com.squareup.picasso.RequestCreator.into(RequestCreator.java:682)
        at com.lazygeniouz.house.ads.HouseAdsNative.setUp(HouseAdsNative.java:174)
        at com.lazygeniouz.house.ads.HouseAdsNative.lambda$loadAds$0$HouseAdsNative(HouseAdsNative.java:91)
        at com.lazygeniouz.house.ads.-$$Lambda$HouseAdsNative$O9qITdYuNoBmCIlXYjxA9yjAJUE.onPostExecute(lambda)
        at com.lazygeniouz.house.ads.helper.JsonPullerTask.onPostExecute(JsonPullerTask.java:28)
        at com.lazygeniouz.house.ads.helper.JsonPullerTask.onPostExecute(JsonPullerTask.java:12)
        at android.os.AsyncTask.finish(AsyncTask.java:667)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6198)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by ItzNotABug** [comment]
Can you share your implementation?

**Comment by ItzNotABug** [comment]
Closing due to inactivity.\
Feel free to reopen if you have more info. on this.
